version: '2'

services:
    boilerplatebackend:
        volumes:
            - .:/boilerplate

            # necessary to prevent OS X node_modules being loaded in:
            - /node_modules

        build:
            context: ./
            dockerfile: ./Dockerfile

        ports:
          - "8080:8080"
          - "8081:8081"
