version: '2'

services:
    backend:
        volumes:
            - .:/backend/

            # necessary to prevent OS X node_modules being loaded in:
            - /backend/node_modules

        build:
            context: ./
            dockerfile: ./backend/Dockerfile
    frontend:
        volumes:
            - .:/frontend

            # necessary to prevent OS X node_modules being loaded in:
            - /frontend/node_modules

        build:
            context: ./
            dockerfile: ./frontend/Dockerfile

        ports:
          - "8080:8080"
